services:
  - type: web
    name: appsiembra-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://app-siembra-jhayler.web.app
      - key: PYTHON_SERVICE_URL
        value: https://app-siembra-python-services.onrender.com
    rootDir: backend

  - type: web
    name: app-siembra-python-services
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5001
    rootDir: python-service
